name: prueba_tecnica
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
    
  tflite_flutter: ^0.9.0       # For TensorFlow Lite
  image_picker: ^0.8.5+3       # For picking images from the gallery
  image: ^4.0.17               # For image processing

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
